version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: prompt_vault_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: prompt_vault_db
      MYSQL_USER: vaultuser
      MYSQL_PASSWORD: vaultpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
